/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ALERTAS_H_RPCGEN
#define _ALERTAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 40

struct presionArterial {
	int sistolica;
	int diastolica;
};
typedef struct presionArterial presionArterial;

struct nodo_indicadores {
	int frecuenciaCardiaca;
	presionArterial sPresionArterial;
	int frecuenciaRespiratoria;
	float temperatura;
	int saturacionOxigeno;
};
typedef struct nodo_indicadores nodo_indicadores;

struct nodo_paciente {
	char nombres[MAXNOM];
	float edad;
	int numHabitacion;
	nodo_indicadores indicadores;
};
typedef struct nodo_paciente nodo_paciente;

#define gestion_alertas 0x20000001
#define gestion_alertas_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define enviarIndicador 1
extern  bool_t * enviarindicador_1(nodo_paciente *, CLIENT *);
extern  bool_t * enviarindicador_1_svc(nodo_paciente *, struct svc_req *);
extern int gestion_alertas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define enviarIndicador 1
extern  bool_t * enviarindicador_1();
extern  bool_t * enviarindicador_1_svc();
extern int gestion_alertas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_presionArterial (XDR *, presionArterial*);
extern  bool_t xdr_nodo_indicadores (XDR *, nodo_indicadores*);
extern  bool_t xdr_nodo_paciente (XDR *, nodo_paciente*);

#else /* K&R C */
extern bool_t xdr_presionArterial ();
extern bool_t xdr_nodo_indicadores ();
extern bool_t xdr_nodo_paciente ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ALERTAS_H_RPCGEN */
