/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "alertas.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <stdio_ext.h>

int random_number(int min_num, int max_num);
void menu();
void msg_indicadores(nodo_paciente objPaciente);
void menu_rangos();
void edad(nodo_paciente *objPaciente);
void llenar_indicadores(nodo_paciente *objPaciente);

void
gestion_alertas_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	nodo_paciente  objPaciente;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_alertas, gestion_alertas_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int op = 0, band = 0, seg = 0, bandOp = 0;
	do{
		menu();
		scanf("%d",&op);

		switch (op)
		{
		case 1:	
			band = 0;
			if(bandOp == 0){
				printf("\nIngrese el numero de la habitación del paciente ");
				printf("\n¡OJO! Debe ser un número entero entre 100 y 999:\n-> ");
				scanf("%d", &objPaciente.numHabitacion);
				__fpurge(stdin);
				while(band == 0){
					if( objPaciente.numHabitacion >= 100 && objPaciente.numHabitacion <= 999 ){
						band = 1;
					}else{					
						printf("\n¡Error! NUMERO HABITACION FUERA DE RANGO");
						printf("\nIngrese el numero de la habitación del paciente");
						printf("\n¡OJO! Debe ser un número entero entre 100 y 999:\n-> ");
						scanf("%d", &objPaciente.numHabitacion);
						__fpurge(stdin);
					}
				}
				printf("\nIngrese nombre(s) y apellidos del paciente:\n-> ");
				fgets(objPaciente.nombres, 40, stdin);
				edad(&objPaciente);
				bandOp++;
				break;
			}else{
				printf("\nYa se ha registrado un paciente. Por favor inicie la lectura de los sensores.\n");
				menu();
				scanf("%d",&op);
			}			
		case 2:	
			if(bandOp == 1){
				llenar_indicadores(&objPaciente);
				msg_indicadores(objPaciente);
				result_1 = enviarindicador_1(&objPaciente, clnt);
				if (result_1 == (bool_t *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				while(1){
					sleep(1);
					seg++;
					if(seg % 10 == 0){
						llenar_indicadores(&objPaciente);
						msg_indicadores(objPaciente);
						result_1 = enviarindicador_1(&objPaciente, clnt);
						if (result_1 == (bool_t *) NULL) {
							clnt_perror (clnt, "call failed");
						}
					}
				}
				break;
			}else{
				printf("\nPor favor ingrese un paciente antes de iniciar la lectura de los sensores.\n");
				menu();
				scanf("%d",&op);
			}
		case 3: 
			printf("=======================\n");
			printf("||   ¡Good bye! :)   ||\n");
			printf("=======================\n");
	                break;
		default:
			printf("\n Opción no permitida. Por favor elija otra opción. \n");
			break;
		}

	}while(op!=3);
			
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_alertas_1 (host);
exit (0);
}

void menu(){

	printf("\n========== MENU DE SENSORES ==========\n");
	printf("1. Ingresar datos del paciente\n");
	printf("2. Comenzar lectura de los sensores\n");
	printf("3. Salir\n");
	printf("======================================\n");
	printf("Por favor digite una opcion: ");
	return;

}

void msg_indicadores(nodo_paciente objPaciente){

	printf("\nEnviando indicadores... \n\n");
	printf("Frecuencia cardiaca: %d\n", objPaciente.indicadores.frecuenciaCardiaca);
	printf("Presion arterial: %d/%d\n", objPaciente.indicadores.sPresionArterial.sistolica, 		objPaciente.indicadores.sPresionArterial.diastolica);
	printf("Frecuencia respiratoria: %d\n", objPaciente.indicadores.frecuenciaRespiratoria);
	printf("Temperatura: %f\n", objPaciente.indicadores.temperatura);
	printf("Saturacion del oxigeno: %d%\n", objPaciente.indicadores.saturacionOxigeno);
	return;

}

void menu_rangos(){
	printf("\n============ RANGOS ============\n");
	printf("1. Nacimiento - 48 semanas (1 anio)\n");
	printf("2. 1 anio y más\n");
	printf("3. Salir\n");
	printf("=================================\n");
	printf("Por favor digite una opcion de acuerdo al rango en donde se encuentre la edad del paciente:\n-> ");
	return;
}

void edad(nodo_paciente *objPaciente){
	int op = 0, band = 0;	 
	menu_rangos();
	scanf("%d",&op);

	switch (op)
	{
	case 1:
			printf("Ingrese su edad (en semanas) \n");
			printf("¡OJO! Edad entre 1 y 48 semanas:\n-> ");
			scanf("%f",&objPaciente->edad);
			while(band == 0){
				if(objPaciente->edad > 0 && objPaciente->edad <= 48){
					band = 1;
					objPaciente->edad = objPaciente->edad/48;
				}else{
					printf("¡Error! EDAD FUERA DE RANGO\n");
					printf("Ingrese su edad (en semanas) \n");
					printf("¡OJO! Edad entre 1 y 48 semanas:\n-> ");
					scanf("%f",&objPaciente->edad);	
				}
			}
		break;
	case 2:
		band = 0;
		printf("Ingrese su edad (en anios) \n");
		printf("¡OJO! Edad mayor a 0 anios:\n-> ");
		scanf("%f",&objPaciente->edad);	
		while(band == 0){
			if( objPaciente->edad > 0 ){
				band = 1;
			}else{
				printf("¡Error! EDAD FUERA DE RANGO\n");
				printf("Ingrese su edad (en anios) \n");
				printf("¡OJO! Edad mayor a 0 anios:\n-> ");
				scanf("%f",&objPaciente->edad);	
			}
		}
		break;
	case 3:
		menu();
	default:
		printf("\n Opción no permitida. Por favor elija otra opción. \n");
		edad(objPaciente);
		break;
	}
	return;
}

void llenar_indicadores(nodo_paciente *objPaciente){
	int frec_card = 0;
	frec_card = random_number(60, 140);
	objPaciente->indicadores.frecuenciaCardiaca = frec_card;
	int pres_art_sist = 0, pres_art_dias = 0;
	pres_art_sist = random_number(70, 140);
	pres_art_dias = random_number(50, 90);
	objPaciente->indicadores.sPresionArterial.sistolica = pres_art_sist;
	objPaciente->indicadores.sPresionArterial.diastolica = pres_art_dias;
	int frec_resp = 0;
	frec_resp = random_number(12, 45);
	objPaciente->indicadores.frecuenciaRespiratoria = frec_resp;
	float temp = 0.0;
	temp = random_number(35, 40);
	objPaciente->indicadores.temperatura = temp;
	int sat_oxi = 0;
	sat_oxi = random_number(90, 100);
	objPaciente->indicadores.saturacionOxigeno = sat_oxi;
	/*
	int frec_card = 0;
	frec_card = random_number(0, 140);
	objPaciente->indicadores.frecuenciaCardiaca = frec_card;
	int pres_art_sist = 0, pres_art_dias = 0;
	pres_art_sist = random_number(0, 140);
	pres_art_dias = random_number(0, 90);
	objPaciente->indicadores.sPresionArterial.sistolica = pres_art_sist;
	objPaciente->indicadores.sPresionArterial.diastolica = pres_art_dias;
	int frec_resp = 0;
	frec_resp = random_number(0, 45);
	objPaciente->indicadores.frecuenciaRespiratoria = frec_resp;
	float temp = 0.0;
	temp = random_number(0, 38);
	objPaciente->indicadores.temperatura = temp;
	int sat_oxi = 0;
	sat_oxi = random_number(1, 101);
	objPaciente->indicadores.saturacionOxigeno = sat_oxi;
	*/
	return;

}

int random_number(int min_num,int max_num){
	int result = 0, high_num = 0, low_num = 0;
	if(min_num < max_num){
		low_num = min_num;
		high_num = max_num + 1;
	}else{
		low_num = max_num + 1;
		high_num = min_num;	
	}
	srand(time(NULL));
	result = (rand() % (high_num - low_num)) + low_num;	
	return result;
}
